import { Injectable, OnModuleInit, OnModuleDestroy } from '@nestjs/common';
import { PrismaClient } from '@prisma/commerce-client';

/**
 * CommercePrismaService — the second Prisma client in this backend.
 *
 * Connects to the BetterDay Commerce Neon project (`betterday-commerce`,
 * id `spring-fire-44871408`) — completely separate from Gurleen's culinary
 * database. This service backs every commerce-* module and is the ONLY way
 * commerce code should read or write customer-facing data.
 *
 * Key distinctions from PrismaService (the culinary client):
 *   - Imports from `@prisma/commerce-client` (not `@prisma/client`), which
 *     is generated by `prisma/commerce/schema.prisma` into
 *     `node_modules/@prisma/commerce-client/`.
 *   - Talks to COMMERCE_DATABASE_URL (not DATABASE_URL).
 *   - Exposes models like Customer, CustomerSession, CustomerOrder,
 *     Subscription, WeeklyCartRecord, RewardPointsTransaction, Coupon,
 *     CustomerCoupon, PaymentMethod, PickupLocation, CustomerAddress,
 *     CustomerAuthToken.
 *
 * DO NOT use this service to query culinary data. Commerce modules that
 * need meal catalog, recipes, or production data should inject the
 * culinary PrismaService alongside this one and query both as needed.
 * Never cross-reference the two schemas via Prisma relations — they live
 * in different databases and there are no FKs between them.
 *
 * Lifecycle mirrors PrismaService: connects on module init, disconnects
 * on module destroy. NestJS calls these automatically during app startup
 * and shutdown.
 *
 * See: backend/prisma/commerce/schema.prisma for the full model set.
 * See: conner/data-model/commerce-neon-setup.md for Neon project details.
 * See: PROJECT_SCOPE.md §10 for the "two Prisma clients, one NestJS app"
 *      bounded-context architecture.
 */
@Injectable()
export class CommercePrismaService
  extends PrismaClient
  implements OnModuleInit, OnModuleDestroy
{
  private connected = false;

  async onModuleInit() {
    // Skip connection if COMMERCE_DATABASE_URL is not configured.
    // This allows the culinary-ops backend to start on Railway (which only
    // has DATABASE_URL for the culinary DB) without crashing. Commerce
    // endpoints will return 500 if hit, but all culinary + corporate
    // endpoints work fine.
    if (!process.env.COMMERCE_DATABASE_URL) {
      console.warn('[CommercePrismaService] COMMERCE_DATABASE_URL not set — commerce modules disabled');
      return;
    }
    try {
      await this.$connect();
      this.connected = true;
    } catch (e) {
      console.warn('[CommercePrismaService] Failed to connect to commerce DB:', (e as Error).message);
    }
  }

  async onModuleDestroy() {
    if (this.connected) {
      await this.$disconnect();
    }
  }
}
