-- ──────────────────────────────────────────────────────────────────
-- SPRWT allergen backfill for Ingredient table
-- Generated: 2026-04-08 from 19-page PDF export of SPRWT admin UI
-- Source: conner/data-model/exports/ingredients-sprwt-allergens-2026-04-08.csv
-- Target branch: conner-local-dev (br-little-hall-aeffmfdm)
--
-- Run manually after reviewing the dry-run output. Only updates rows
-- where the current allergen_tags is empty — won't overwrite any
-- existing manual tags. Match is case-insensitive, with trailing
-- '#1234567' SKU tokens stripped from the display_name.
-- ──────────────────────────────────────────────────────────────────

WITH sprwt(norm_name, allergens, sprwt_display_name) AS (
  VALUES
  ('4oz salmon', ARRAY['Fish']::text[], '4oz Salmon'),
  ('gordon choice 7 grain blend rice mix', ARRAY['Gluten', 'Wheat']::text[], 'Gordon Choice 7 Grain Blend Rice Mix'),
  ('8oz steak sirloin', ARRAY[]::text[], '8oz Steak Sirloin'),
  ('whole almonds', ARRAY['Tree Nuts']::text[], 'Whole Almonds'),
  ('almond butter', ARRAY['Tree Nuts']::text[], 'Almond Butter'),
  ('sliced almonds', ARRAY['Tree Nuts']::text[], 'Sliced Almonds'),
  ('aquafaba powder', ARRAY[]::text[], 'Aquafaba Powder'),
  ('canned cut baby corn', ARRAY[]::text[], 'Canned Cut Baby Corn'),
  ('bacon crumble', ARRAY[]::text[], 'Bacon Crumble'),
  ('whole beef chuck flat, fresh', ARRAY[]::text[], 'Whole Beef Chuck Flat, Fresh'),
  ('tavolini italian meatballs 2oz', ARRAY['Dairy', 'Gluten', 'Wheat']::text[], 'Tavolini Italian Meatballs 2oz'),
  ('beef pastrami', ARRAY[]::text[], 'Beef Pastrami'),
  ('intercity custom meats 2oz prime rib 3in slider beef burgers, frozen', ARRAY['Wheat']::text[], 'Intercity Custom Meats 2oz Prime Rib 3in Slider Beef Burgers, Frozen'),
  ('intercity custom meats flattened beef steaks, grade-aa+ frozen', ARRAY[]::text[], 'Intercity Custom Meats Flattened Beef Steaks, Grade-AA+ Frozen'),
  ('intercity custom meats (icm) beef strips, 3x1/2x1/4in', ARRAY[]::text[], 'Intercity Custom Meats (ICM) Beef Strips, 3X1/2X1/4in'),
  ('whole red beets', ARRAY[]::text[], 'Whole Red Beets'),
  ('biscoff cookies a', ARRAY['Gluten', 'Wheat']::text[], 'Biscoff Cookies A'),
  ('ace brioche burger buns', ARRAY['Dairy', 'Gluten']::text[], 'ACE Brioche Burger Buns'),
  ('4oz chuck beef burger patties', ARRAY['Gluten', 'Wheat']::text[], '4oz Chuck Beef Burger Patties'),
  ('rose hill cajun blend spice seasoning', ARRAY[]::text[], 'Rose Hill Cajun Blend Spice Seasoning'),
  ('cannelloni', ARRAY['Gluten', 'Wheat']::text[], 'Cannelloni'),
  ('cashew butts (tootsi)', ARRAY['Tree Nuts']::text[], 'Cashew Butts (Tootsi)'),
  ('cashew butter (tootsi)', ARRAY['Tree Nuts']::text[], 'Cashew Butter (Tootsi)'),
  ('sliced mild cheddar cheese', ARRAY['Dairy']::text[], 'Sliced Mild Cheddar Cheese'),
  ('4oz boneless skinless seasoned chicken breasts', ARRAY[]::text[], '4oz Boneless Skinless Seasoned Chicken Breasts'),
  ('chicken thighs', ARRAY[]::text[], 'Chicken Thighs'),
  ('canned chickpea', ARRAY[]::text[], 'Canned Chickpea'),
  ('glod plum chinkiang vinegar', ARRAY['Gluten']::text[], 'Glod Plum Chinkiang Vinegar'),
  ('maple leaf raw scratch meat chorizo', ARRAY[]::text[], 'Maple Leaf Raw Scratch Meat Chorizo'),
  ('cilantro', ARRAY[]::text[], 'Cilantro'),
  ('frozen corn nibblets (no name brand)', ARRAY[]::text[], 'Frozen Corn Nibblets (No Name Brand)'),
  ('dairyland cottage cheese, 2 percent', ARRAY['Dairy']::text[], 'Dairyland Cottage Cheese, 2 Percent'),
  ('couscous', ARRAY['Gluten', 'Wheat']::text[], 'Couscous'),
  ('cream cheese', ARRAY['Dairy']::text[], 'Cream Cheese'),
  ('farkay dry chow mein noodles', ARRAY['Eggs', 'Gluten', 'Wheat']::text[], 'Farkay Dry Chow Mein Noodles'),
  ('gordon choice diced chicken, 1/2 inch, 20 percent white, 80 percent dark, cooked, frozen', ARRAY[]::text[], 'Gordon Choice Diced Chicken, 1/2 Inch, 20 Percent White, 80 Percent Dark, Cooked, Frozen'),
  ('clubhouse dill pickle seasoning', ARRAY[]::text[], 'Clubhouse Dill Pickle Seasoning'),
  ('liquid egg whites', ARRAY['Eggs']::text[], 'Liquid Egg Whites'),
  ('egg solutions bacon cheddar egg bites', ARRAY['Dairy', 'Eggs']::text[], 'Egg Solutions Bacon Cheddar Egg Bites'),
  ('egg solutions spinach & red pepper egg bites', ARRAY['Dairy', 'Eggs']::text[], 'Egg Solutions Spinach & Red Pepper Egg Bites'),
  ('eggplant', ARRAY[]::text[], 'Eggplant'),
  ('extra lean ground turkey', ARRAY[]::text[], 'Extra Lean Ground Turkey'),
  ('pitas inc, falafal patties', ARRAY['Gluten', 'Wheat']::text[], 'Pitas Inc, Falafal Patties'),
  ('kitchen essentials feta cheese', ARRAY['Dairy']::text[], 'Kitchen Essentials Feta Cheese'),
  ('president crumbled dairy feta', ARRAY['Dairy']::text[], 'President Crumbled Dairy Feta'),
  ('golden boy fish sauce', ARRAY['Fish']::text[], 'Golden Boy Fish Sauce'),
  ('gordon choice bleached all purpose flour', ARRAY['Gluten', 'Wheat']::text[], 'Gordon Choice Bleached All Purpose Flour'),
  ('velo fresh mozza', ARRAY['Dairy']::text[], 'Velo Fresh Mozza'),
  ('gordon choice fried patty eggs', ARRAY['Eggs']::text[], 'Gordon Choice Fried Patty Eggs'),
  ('barilla gf penne', ARRAY[]::text[], 'BARILLA GF Penne'),
  ('gf rotini pasta', ARRAY[]::text[], 'GF Rotini Pasta'),
  ('gf spaghetti', ARRAY[]::text[], 'GF Spaghetti'),
  ('gochujang', ARRAY[]::text[], 'Gochujang'),
  ('gordon choice zesty orange ginger sauce', ARRAY['Wheat']::text[], 'Gordon Choice Zesty Orange Ginger Sauce'),
  ('mary''s organic crackers graham honey kookies', ARRAY['Sesame']::text[], 'Mary''s Organic Crackers Graham Honey Kookies'),
  ('crystal springs greek yogurt', ARRAY['Dairy']::text[], 'Crystal Springs Greek Yogurt'),
  ('green curry paste', ARRAY[]::text[], 'Green Curry Paste'),
  ('green lentils', ARRAY[]::text[], 'Green lentils'),
  ('chicken protein packs', ARRAY[]::text[], 'Chicken Protein Packs'),
  ('chicken breasts, grilled, 3oz, cooked, individually quick frozen', ARRAY[]::text[], 'Chicken Breasts, Grilled, 3oz, Cooked, Individually Quick Frozen'),
  ('gusta vegan cheddar cheese, block', ARRAY['Wheat']::text[], 'Gusta Vegan Cheddar Cheese, Block'),
  ('olymel smoked ham, whole, boneless, express, carve, 19pct protein, fresh', ARRAY[]::text[], 'Olymel Smoked Ham, Whole, Boneless, Express, Carve, 19Pct Protein, Fresh'),
  ('hemp seeds', ARRAY[]::text[], 'Hemp Seeds'),
  ('hoisin sauce', ARRAY['Gluten']::text[], 'Hoisin Sauce'),
  ('honey', ARRAY[]::text[], 'Honey'),
  ('olives, large pitted kalamata', ARRAY[]::text[], 'Olives, Large Pitted Kalamata'),
  ('lactantia, whip cream 35%', ARRAY['Dairy']::text[], 'Lactantia, Whip Cream 35%'),
  ('lean ground beef', ARRAY[]::text[], 'Lean Ground Beef'),
  ('let''s pasta, gnocchi pasta, frozen', ARRAY['Eggs', 'Gluten']::text[], 'Let''s Pasta, Gnocchi Pasta, Frozen'),
  ('mango red thai curry sauce (cashew, soy)', ARRAY['Tree Nuts']::text[], 'Mango Red Thai Curry Sauce (Cashew, Soy)'),
  ('kapow mini vegetable samosas, appetizer', ARRAY['Gluten', 'Wheat']::text[], 'Kapow Mini Vegetable Samosas, Appetizer'),
  ('montreal steak spice', ARRAY[]::text[], 'Montreal Steak Spice'),
  ('pre-sliced mushroom', ARRAY[]::text[], 'Pre-Sliced Mushroom'),
  ('tavolini orzo pasta', ARRAY['Gluten', 'Wheat']::text[], 'Tavolini Orzo Pasta'),
  ('tre stelle paneer cheese', ARRAY['Dairy']::text[], 'Tre Stelle Paneer Cheese'),
  ('shredded parmesan cheese', ARRAY['Dairy']::text[], 'Shredded Parmesan Cheese'),
  ('peanut butter', ARRAY['Peanuts', 'Tree Nuts']::text[], 'Peanut Butter'),
  ('pre-diced peanuts', ARRAY['Peanuts']::text[], 'Pre-Diced Peanuts'),
  ('sunspun penne', ARRAY['Gluten', 'Wheat']::text[], 'SUNSPUN Penne'),
  ('peperoncini pepper', ARRAY[]::text[], 'Peperoncini Pepper'),
  ('pepperoncini', ARRAY[]::text[], 'Pepperoncini'),
  ('fresh whole pineapple', ARRAY[]::text[], 'Fresh Whole Pineapple'),
  ('perfectly imperfect frozen pineapple', ARRAY[]::text[], 'Perfectly Imperfect Frozen Pineapple'),
  ('whole unshelled pistachio', ARRAY['Tree Nuts']::text[], 'Whole Unshelled Pistachio'),
  ('pita bread greek style (kronos brand)', ARRAY['Wheat']::text[], 'Pita Bread Greek Style (Kronos Brand)'),
  ('gordon choice plain omelettes', ARRAY['Dairy', 'Eggs']::text[], 'Gordon Choice Plain Omelettes'),
  ('gordon choice plant based meatballs', ARRAY['Gluten', 'Wheat']::text[], 'Gordon Choice Plant Based Meatballs'),
  ('pork butt', ARRAY[]::text[], 'Pork Butt'),
  ('jimmy dean pork sausage patties', ARRAY[]::text[], 'Jimmy Dean Pork Sausage Patties'),
  ('provolone cheese', ARRAY['Dairy']::text[], 'Provolone Cheese'),
  ('tri-color quinoa', ARRAY[]::text[], 'Tri-Color Quinoa'),
  ('red curry paste', ARRAY[]::text[], 'Red Curry Paste'),
  ('red lentils', ARRAY[]::text[], 'Red Lentils'),
  ('roasted eggplant', ARRAY[]::text[], 'Roasted Eggplant'),
  ('rotini pasta', ARRAY['Gluten', 'Wheat']::text[], 'Rotini Pasta'),
  ('s&b nanami togarashi spice', ARRAY['Sesame']::text[], 'S&B Nanami Togarashi Spice'),
  ('knorr professional gravy mix', ARRAY['Dairy']::text[], 'Knorr Professional Gravy Mix'),
  ('samosas, vegetable, frozen appetizer, vegan', ARRAY['Peanuts', 'Wheat']::text[], 'Samosas, Vegetable, Frozen Appetizer, Vegan'),
  ('gordon choice, plant based, sausage patties, frozen', ARRAY[]::text[], 'Gordon Choice, Plant Based, Sausage Patties, Frozen'),
  ('scoobi doo pasta', ARRAY['Wheat']::text[], 'Scoobi Doo Pasta'),
  ('soya and sesame oil', ARRAY['Sesame']::text[], 'Soya And Sesame Oil'),
  ('black sesame seeds', ARRAY['Sesame']::text[], 'Black Sesame Seeds'),
  ('white sesame seeds', ARRAY['Sesame']::text[], 'White Sesame Seeds'),
  ('mina shawarma chicken shawarma, strip cooked frozen', ARRAY[]::text[], 'Mina Shawarma Chicken Shawarma, Strip Cooked Frozen'),
  ('shredded nacho cheese blend', ARRAY['Dairy']::text[], 'Shredded Nacho Cheese Blend'),
  ('gordon choice shredded mild cheddar cheese', ARRAY['Dairy']::text[], 'Gordon Choice Shredded Mild Cheddar Cheese'),
  ('shredded mozzarella cheese + edam', ARRAY['Dairy']::text[], 'Shredded Mozzarella Cheese + Edam'),
  ('shrimp', ARRAY['Shellfish']::text[], 'Shrimp'),
  ('cab sirloin flap beef steaks, frozen', ARRAY[]::text[], 'CAB Sirloin Flap Beef Steaks, Frozen'),
  ('sliced cheddar cheese', ARRAY['Dairy']::text[], 'Sliced Cheddar Cheese'),
  ('sliced ciabatta, 3x7in, thaw and serve (110g)', ARRAY['Gluten', 'Wheat']::text[], 'Sliced Ciabatta, 3x7in, Thaw and Serve (110g)'),
  ('brickman''s sliced natural mozzarella cheese, 14g', ARRAY['Dairy']::text[], 'Brickman''s Sliced Natural Mozzarella Cheese, 14G'),
  ('gordon choice 4oz sliced philly beef steaks', ARRAY[]::text[], 'Gordon Choice 4oz Sliced Philly Beef Steaks'),
  ('sliced swiss cheese', ARRAY['Dairy']::text[], 'Sliced Swiss Cheese'),
  ('ichester smoked cheddar applewood cheese', ARRAY['Dairy']::text[], 'Ichester Smoked Cheddar Applewood Cheese'),
  ('t&t buckwheat soba noodles', ARRAY['Gluten']::text[], 'T&T Buckwheat Soba Noodles'),
  ('gordon choice sour cream', ARRAY['Dairy']::text[], 'Gordon Choice Sour Cream'),
  ('butler''s soy curls', ARRAY[]::text[], 'Butler''s Soy Curls'),
  ('spaghetti', ARRAY['Gluten', 'Wheat']::text[], 'Spaghetti'),
  ('everything bagel spice', ARRAY[]::text[], 'Everything Bagel Spice'),
  ('spicy tag for dislikes', ARRAY[]::text[], 'Spicy Tag for Dislikes'),
  ('spolumbo''s chicken apple sausages', ARRAY[]::text[], 'Spolumbo''s Chicken Apple Sausages'),
  ('sriracha tabasco sauce', ARRAY[]::text[], 'Sriracha Tabasco Sauce'),
  ('intercity custom meats 1in diced beef', ARRAY[]::text[], 'Intercity Custom Meats 1in Diced Beef'),
  ('trophy foods roasted salted sunflower seeds', ARRAY[]::text[], 'Trophy Foods Roasted Salted Sunflower Seeds'),
  ('sunspun linguini pasta', ARRAY['Gluten', 'Wheat']::text[], 'Sunspun Linguini Pasta'),
  ('tahini (tamam brand)', ARRAY['Sesame']::text[], 'Tahini (TAMAM Brand)'),
  ('tavolini sundried tomato pesto sauce', ARRAY['Dairy']::text[], 'Tavolini Sundried Tomato Pesto Sauce'),
  ('stanislaus, al dente pasta, sauce', ARRAY[]::text[], 'Stanislaus, Al Dente Pasta, Sauce'),
  ('tavolini tri-colour cheese tortellini pasta', ARRAY['Dairy', 'Wheat']::text[], 'Tavolini Tri-Colour Cheese Tortellini Pasta'),
  ('tortilla chip', ARRAY[]::text[], 'Tortilla Chip'),
  ('tri color pearl couscous', ARRAY['Gluten', 'Wheat']::text[], 'Tri Color Pearl Couscous'),
  ('turkey bacon', ARRAY[]::text[], 'Turkey Bacon'),
  ('llydale turkey sausages, gourmet frozen', ARRAY[]::text[], 'Llydale Turkey Sausages, Gourmet Frozen'),
  ('udon noodles', ARRAY['Gluten', 'Wheat']::text[], 'Udon Noodles'),
  ('field roast, original creamy sliced alternative, cheese', ARRAY['Sesame']::text[], 'Field Roast, Original Creamy Sliced Alternative, Cheese'),
  ('gordon signature vegetable medley dim sum, vegan', ARRAY['Sesame', 'Wheat']::text[], 'Gordon Signature Vegetable Medley Dim Sum, Vegan'),
  ('kirkland signature shelled walnuts', ARRAY['Tree Nuts']::text[], 'Kirkland Signature Shelled Walnuts'),
  ('10 inch dempster''s white tortilla', ARRAY['Gluten', 'Wheat']::text[], '10 inch Dempster''s White Tortilla'),
  ('gordon choice liquid whole eggs', ARRAY['Eggs']::text[], 'Gordon Choice Liquid Whole Eggs'),
  ('beatrice milk jug homogenized 3.25% 4l', ARRAY['Dairy']::text[], 'Beatrice Milk Jug Homogenized 3.25% 4L'),
  ('10in whole wheat flour tortilla wraps', ARRAY['Gluten', 'Wheat']::text[], '10in Whole Wheat Flour Tortilla Wraps'),
  ('frozen yellow peanut curry base', ARRAY['Peanuts', 'Tree Nuts']::text[], 'Frozen Yellow Peanut Curry Base'),
  ('green zucchini', ARRAY[]::text[], 'Green Zucchini')
)
UPDATE "Ingredient" i
SET
  allergen_tags = s.allergens,
  updated_at = NOW()
FROM sprwt s
WHERE LOWER(REGEXP_REPLACE(i.display_name, E'\s*#\d+\s*$', '')) = s.norm_name
  AND cardinality(s.allergens) > 0
  AND (i.allergen_tags IS NULL OR cardinality(i.allergen_tags) = 0)
RETURNING i.display_name, i.allergen_tags;
